name: synpop
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py312h06a4308_0
  - anaconda-anon-usage=0.4.4=py312hfc0e8ea_100
  - anyio=4.6.2=py312h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=24.2.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - boltons=23.0.0=py312h06a4308_0
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312h06a4308_0
  - conda=24.9.2=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=24.7.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py312h06a4308_0
  - conda-package-streaming=0.10.0=py312h06a4308_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cryptography=42.0.5=py312hdda0065_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py312h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - flatbuffers=24.3.25=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozendict=2.4.2=py312h06a4308_0
  - fsspec=2024.6.1=py312h06a4308_0
  - gast=0.5.3=pyhd3eb1b0_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.62.2=py312h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py312h06a4308_0
  - h5py=3.11.0=py312h34c39bb_0
  - hdf5=1.12.1=h2b7332f_3
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - ipykernel=6.29.5=py312h06a4308_0
  - ipython=8.27.0=py312h06a4308_0
  - ipywidgets=8.1.2=py312h06a4308_0
  - jedi=0.19.1=py312h06a4308_0
  - jinja2=3.1.4=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.0.0=py312h06a4308_9
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.10.0=py312h06a4308_0
  - jupyter_server=2.14.1=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.2.5=py312h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.10=py312h06a4308_0
  - keras=3.4.1=py312h06a4308_0
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarchive=3.6.2=hfab0078_4
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.7.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libmamba=1.5.8=hfe524e5_2
  - libmambapy=1.5.8=py312h2dafd23_2
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.24=he621ea3_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py312h06a4308_0
  - markdown-it-py=2.2.0=py312h06a4308_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.2=py312h06a4308_0
  - matplotlib-base=3.9.2=py312h66fe004_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mdurl=0.1.0=py312h06a4308_0
  - menuinst=2.1.2=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - ml_dtypes=0.4.0=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - namex=0.0.7=py312h06a4308_0
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.16.4=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - networkx=3.3=py312h06a4308_0
  - notebook=7.2.2=py312h06a4308_1
  - notebook-shim=0.2.3=py312h06a4308_0
  - numexpr=2.8.7=py312he7dcb8a_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.12.1=py312hdb19cb5_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py312h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.0.0=py312h06a4308_1
  - ply=3.11=py312h06a4308_1
  - prometheus_client=0.14.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py312h12ddb61_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - pyparsing=3.1.2=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.16.2=py312h06a4308_0
  - python-flatbuffers=24.3.25=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.3.0=cpu_py312hde650b8_1
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - qtconsole=5.6.0=py312h06a4308_0
  - qtpy=2.4.1=py312h06a4308_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rich=13.7.1=py312h06a4308_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - ruamel.yaml=0.17.21=py312h5eee18b_0
  - seaborn=0.13.2=py312h06a4308_0
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=72.1.0=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.2=py312h06a4308_0
  - tensorboard=2.17.0=py312h06a4308_0
  - tensorboard-data-server=0.7.0=py312h52d8a92_1
  - tensorflow=2.17.0=cpu_py312hbca4264_0
  - tensorflow-base=2.17.0=cpu_py312he58cd35_0
  - tensorflow-estimator=2.17.0=cpu_py312hfedf350_0
  - termcolor=2.1.0=py312h06a4308_0
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py312h5eee18b_0
  - tqdm=4.66.4=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - truststore=0.8.0=py312h06a4308_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.2=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - werkzeug=3.0.3=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - widgetsnbextension=4.0.10=py312h06a4308_0
  - wrapt=1.14.1=py312h5eee18b_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.22.0=py312h2c38b39_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - babel==2.17.0
      - commonmark==0.9.1
      - et-xmlfile==2.0.0
      - faicons==0.2.2
      - formulaic==1.1.1
      - great-tables==0.17.0
      - htmltools==0.6.0
      - importlib-resources==6.5.2
      - interface-meta==1.3.0
      - joblib==1.4.2
      - lets-plot==4.6.1
      - llvmlite==0.44.0
      - narwhals==1.31.0
      - numba==0.61.0
      - openpyxl==3.1.5
      - palettable==3.3.3
      - pyfixest==0.28.0
      - pypng==0.20220715.0
      - scipy==1.15.2
      - tabulate==0.9.0
      - zipp==3.21.0
prefix: /home/jlenti/miniconda3
