name: housing-climate
dependencies:
  - python=3.11
  - jupyter=1.0
  - matplotlib=3.7
  - numpy=1.25
  - seaborn=0.12
  - pandas=2.0
  - pyspark=3.4
  - scipy=1.11
  - scikit-learn=1.2
  - statsmodels=0.14
  - xgboost=1.7
  - geopandas=0.14
  - tqdm=4.66
  - joblib=1.4
  - logging=0.5
  - shapely=2.0
  - rasterio=1.3
  - pickle=4.0