name: synpop
channels:
  - defaults
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - _py-xgboost-mutex=2.0=cpu_0
  - affine=2.3.0=pyhd3eb1b0_0
  - anyio=4.7.0=py311h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_1
  - asttokens=3.0.0=py311h06a4308_0
  - async-lru=2.0.4=py311h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.3.0=py311h06a4308_0
  - aws-c-auth=0.7.22=h96bc93b_2
  - aws-c-cal=0.6.14=h88a6e22_1
  - aws-c-common=0.9.19=h4ab18f5_0
  - aws-c-compression=0.2.18=h83b837d_6
  - aws-c-event-stream=0.4.2=ha47c788_12
  - aws-c-http=0.8.1=h29d6fba_17
  - aws-c-io=0.14.8=h21d4f22_5
  - aws-c-mqtt=0.10.4=h759edc4_4
  - aws-c-s3=0.5.9=h594631b_3
  - aws-c-sdkutils=0.1.16=h83b837d_2
  - aws-checksums=0.1.18=h83b837d_6
  - aws-crt-cpp=0.26.9=he3a8b3b_0
  - aws-sdk-cpp=1.11.329=hba8bd5f_3
  - babel=2.16.0=py311h06a4308_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - blas=1.0=openblas
  - bleach=6.2.0=py311h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py311hf4808d0_0
  - branca=0.6.0=py311h06a4308_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - brotlicffi=1.0.9.2=py311h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.7.14=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - cfitsio=3.470=h5893167_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py311h06a4308_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - folium=0.14.0=py311h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py311h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - freexl=2.0.0=hf309648_0
  - gdal=3.6.2=py311ha0db937_9
  - geopandas=1.1.0=pyhd8ed1ab_0
  - geopandas-base=1.1.0=pyha770c72_0
  - geos=3.10.6=h6a678d5_0
  - geotiff=1.7.0=h2a26cda_3
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.16.0=py311h06a4308_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - httpcore=1.0.9=py311h06a4308_0
  - httpx=0.28.1=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - ipykernel=6.29.5=py311h06a4308_1
  - ipython=9.1.0=py311h06a4308_0
  - ipython_pygments_lexers=1.1.1=py311h06a4308_0
  - ipywidgets=8.1.5=py311h06a4308_0
  - jedi=0.19.2=py311h06a4308_0
  - jinja2=3.1.6=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json-c=0.16=h5eee18b_0
  - json5=0.9.25=py311h06a4308_0
  - jsonschema=4.23.0=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter=1.0.0=py311h06a4308_9
  - jupyter-lsp=2.2.5=py311h06a4308_0
  - jupyter_client=8.6.3=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.8.1=py311h06a4308_0
  - jupyter_events=0.12.0=py311h06a4308_0
  - jupyter_server=2.16.0=py311h06a4308_0
  - jupyter_server_terminals=0.5.3=py311h06a4308_0
  - jupyterlab=4.4.4=py311h06a4308_0
  - jupyterlab_pygments=0.3.0=py311h06a4308_0
  - jupyterlab_server=2.27.3=py311h06a4308_0
  - jupyterlab_widgets=3.0.15=py311h06a4308_0
  - kealib=1.5.0=hd940352_1
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarrow=13.0.0=h34ad07a_42_cpu
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.71=h39aace5_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgdal=3.6.2=he9acc32_9
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgoogle-cloud=2.24.0=h2736e30_0
  - libgoogle-cloud-storage=2.24.0=h3d9a0c8_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.16=h5eee18b_3
  - libkml=1.3.0=h096b73e_7
  - libllvm14=14.0.6=hecde1de_4
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnl=3.11.0=hb9d3cd8_0
  - libopenblas=0.3.29=ha39b09d_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libre2-11=2024.02.01=h2f2cdcf_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialite=5.1.0=h798b768_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=256.9=h2774228_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.5.1=hffd6297_1
  - libudev1=257.4=h9a4d06a_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxgboost=1.7.6=h6a678d5_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzip=1.8.0=h6ac8c49_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=17.0.6=h6c133c5_0
  - lz4-c=1.9.4=h6a678d5_1
  - mapclassify=2.5.0=py311h06a4308_0
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.7.2=py311h06a4308_0
  - matplotlib-base=3.7.2=py311ha02d727_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - minizip=4.0.3=hf59b114_0
  - mistune=3.1.2=py311h06a4308_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.10.2=py311h06a4308_0
  - nbconvert=7.16.6=py311h06a4308_0
  - nbconvert-core=7.16.6=py311h06a4308_0
  - nbconvert-pandoc=7.16.6=py311h06a4308_0
  - nbformat=5.10.4=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - networkx=3.4.2=py311h06a4308_0
  - notebook=7.4.4=py311h06a4308_0
  - notebook-shim=0.2.4=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.11.0=py311hbaae466_0
  - numpy=1.25.2=py311h24aa872_0
  - numpy-base=1.25.2=py311hbfb1bba_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.5.1=h7b32b05_0
  - orc=2.0.1=h2d29ad5_0
  - overrides=7.4.0=py311h06a4308_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.0.3=py311ha02d727_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py311h06a4308_0
  - patsy=1.0.1=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py311h06a4308_0
  - pillow=11.1.0=py311hcea889d_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.7=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - poppler=24.09.0=hcf11d46_1
  - poppler-data=0.4.11=h06a4308_1
  - proj=9.3.1=he5811b7_0
  - prometheus_client=0.21.1=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=1.7.6=py311h06a4308_0
  - py4j=0.10.9.7=py311h06a4308_0
  - pyarrow=13.0.0=py311hd5e4297_42_cpu
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py311h06a4308_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pyproj=3.6.1=py311h76fdc58_1
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - pysocks=1.7.1=py311h06a4308_0
  - pyspark=3.4.1=py311h06a4308_0
  - python=3.11.13=h1a3bd86_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.20.0=py311h06a4308_0
  - python-json-logger=3.2.1=py311h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.3.0=cpu_py311h0178f48_1
  - pytz=2025.2=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - qhull=2020.2=hdb19cb5_2
  - qt-main=5.15.2=hb6262e9_12
  - qtconsole=5.6.1=py311h06a4308_1
  - qtpy=2.4.1=py311h06a4308_0
  - rasterio=1.3.10=py311h7aa6599_0
  - rdma-core=55.0=h5888daf_0
  - re2=2024.02.01=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - requests=2.32.4=py311h06a4308_0
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rpds-py=0.22.3=py311h4aa5aa6_0
  - s2n=1.4.15=he19d79f_0
  - scikit-learn=1.2.2=py311h6a678d5_1
  - scipy=1.11.4=py311h24aa872_0
  - send2trash=1.8.2=py311h06a4308_1
  - setuptools=78.1.1=py311h06a4308_0
  - shapely=2.0.6=py311h6f81d3c_0
  - sip=6.7.12=py311h6a678d5_1
  - six=1.17.0=py311h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py311h06a4308_0
  - snuggs=1.4.7=pyhd3eb1b0_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.4=py311h5eee18b_0
  - terminado=0.17.1=py311h06a4308_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tiledb=2.3.3=h77177df_3
  - tinycss2=1.4.0=py311h06a4308_0
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing-extensions=4.12.2=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ucx=1.16.0=h209287a_5
  - unicodedata2=15.1.0=py311h5eee18b_1
  - uriparser=0.9.8=h451ca9b_0
  - urllib3=2.5.0=py311h06a4308_0
  - wcwidth=0.2.13=py311h06a4308_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - widgetsnbextension=4.0.13=py311h06a4308_0
  - xerces-c=3.2.4=h6a678d5_1
  - xgboost=1.7.6=py311h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2022.9.0=py311h06a4308_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - commonmark==0.9.1
      - faicons==0.2.2
      - filelock==3.18.0
      - fiona==1.9.6
      - formulaic==1.2.0
      - fsspec==2025.7.0
      - great-tables==0.18.0
      - htmltools==0.6.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - interface-meta==1.3.0
      - ipfn==1.4.4
      - lets-plot==4.6.2
      - llvmlite==0.44.0
      - narwhals==1.47.0
      - numba==0.61.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - palettable==3.3.3
      - polars==1.31.0
      - pyfixest==0.26.0
      - pyogrio==0.11.0
      - pypng==0.20220715.0
      - pyrsistent==0.20.0
      - seaborn==0.13.2
      - spatial-autocorrelation==0.0.1a0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tqdm==4.66.4
      - triton==2.3.0
      - wrapt==1.17.2
      - zipp==3.23.0
