name: synpop
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas=1.0
  - jupyter=1.0
  - matplotlib=3.7
  - numpy=1.25
  - pandas=2.0
  - pip=25.1
  - python=3.11
  - scikit-learn=1.2
  - scipy=1.11
  - statsmodels=0.14
  - tqdm=4.66
  - joblib=1.4
  - shapely=2.0
  - rasterio=1.3
  - pytorch==2.3
  - pip:
      - importlib-metadata==8.7
      - importlib-resources==6.5
      - numba==0.61.2
      - pyfixest==0.30
      - seaborn==0.13
      - spatial-autocorrelation==0.0.1a0
      - torch==2.3